export type ToolCategory = 'pdf' | 'conversion' | 'security' | 'utility';

export interface ToolDefinition {
  id: string;
  slug: string;
  name: string;
  category: ToolCategory;
  description: string;
  directAnswer: string;
  popular?: boolean;
  acceptedFormats: string[];
  outputFormat: string;
  canonicalPath: string;
}

export const toolsRegistry: ToolDefinition[] = [
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    category: 'pdf',
    description: 'Reduce PDF file size without sacrificing readability or document formatting.',
    directAnswer: 'Compress PDF decreases file size by stripping redundant metadata, downsampling uncompressed bitmap images, and re-encoding font streams entirely within your browser.',
    popular: true,
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/compress-pdf',
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    category: 'pdf',
    description: 'Combine multiple PDF documents into a single, cohesive file in custom sequence.',
    directAnswer: 'Merge PDF concatenates independent PDF document streams into a unified document while preserving internal bookmark trees and page coordinate matrices.',
    popular: true,
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/merge-pdf',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Split PDF',
    category: 'pdf',
    description: 'Extract custom page ranges or separate all pages into individual PDF files.',
    directAnswer: 'Split PDF isolates selected page indexes from a source document and compiles new standalone PDF files without re-encoding vector assets.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/split-pdf',
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'pdf',
    description: 'Permanently rotate individual pages or entire documents by 90, 180, or 270 degrees.',
    directAnswer: 'Rotate PDF modifies the rotational viewport dictionary of targeted pages permanently without altering underlying text layers.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/rotate-pdf',
  },
  {
    id: 'delete-pdf-pages',
    slug: 'delete-pdf-pages',
    name: 'Delete Pages',
    category: 'pdf',
    description: 'Visually select and permanently purge unwanted pages from any PDF document.',
    directAnswer: 'Delete PDF Pages removes specified page reference nodes from the document catalog tree and optimizes the remaining page sequence.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/delete-pdf-pages',
  },
  {
    id: 'extract-pdf-pages',
    slug: 'extract-pdf-pages',
    name: 'Extract Pages',
    category: 'pdf',
    description: 'Extract specific pages to generate a clean, standalone PDF file.',
    directAnswer: 'Extract Pages copies selected page objects and fonts into a newly initialized PDF structure while retaining source fidelity.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/extract-pdf-pages',
  },
  {
    id: 'rearrange-pdf-pages',
    slug: 'rearrange-pdf-pages',
    name: 'Rearrange Pages',
    category: 'pdf',
    description: 'Reorder document page sequence with a visual drag-and-drop workspace.',
    directAnswer: 'Rearrange Pages rebuilds the PDF page tree array into a new user-defined order with zero quality loss.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/rearrange-pdf-pages',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'conversion',
    description: 'Convert PDF files into editable Microsoft Word (.docx) documents with layout fidelity.',
    directAnswer: 'PDF to Word reconstructs text runs, structural tables, and graphical layouts from PDF bitstreams into native OpenXML Word documents.',
    popular: true,
    acceptedFormats: ['.pdf'],
    outputFormat: '.docx',
    canonicalPath: '/tools/pdf-to-word',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'conversion',
    description: 'Convert Microsoft Word (.docx) documents into standardized, publication-ready PDFs.',
    directAnswer: 'Word to PDF renders OpenXML typography, margins, and embedded assets into standardized PDF vector coordinate streams.',
    acceptedFormats: ['.docx', '.doc'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/word-to-pdf',
  },
  {
    id: 'pdf-to-image',
    slug: 'pdf-to-image',
    name: 'PDF to Image',
    category: 'conversion',
    description: 'Render and extract document pages as high-resolution JPG or PNG image files.',
    directAnswer: 'PDF to Image rasterizes vector page viewports at selectable DPI densities directly to JPEG or PNG canvas streams.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.png',
    canonicalPath: '/tools/pdf-to-image',
  },
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    category: 'conversion',
    description: 'Combine raster images (JPG, PNG, WebP) into a structured PDF document.',
    directAnswer: 'Image to PDF encapsulates raster image frames into standardized PDF page bounding boxes with auto-oriented margins.',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/image-to-pdf',
  },
  {
    id: 'ocr',
    slug: 'ocr',
    name: 'OCR Searchable PDF',
    category: 'utility',
    description: 'Extract and embed searchable text layers into scanned documents using local OCR.',
    directAnswer: 'OCR recognizes optical characters from bitmap scans and injects an invisible, selectable text layer positioned over original words.',
    popular: true,
    acceptedFormats: ['.pdf', '.jpg', '.png'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/ocr',
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'security',
    description: 'Apply custom text or image watermark stamps with precise opacity and angle controls.',
    directAnswer: 'Watermark PDF stamps a transparent vector or raster layer onto each document page canvas prior to stream export.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/watermark-pdf',
  },
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    name: 'Protect PDF',
    category: 'security',
    description: 'Encrypt your PDF with standard AES-256 password protection to restrict access.',
    directAnswer: 'Protect PDF computes a cryptographic cipher key from user passwords to encrypt all internal object streams with AES-256.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/protect-pdf',
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'security',
    description: 'Decrypt and remove password security permissions from authorized PDF documents.',
    directAnswer: 'Unlock PDF validates authorization credentials and writes a clean document stream with encryption dictionaries cleared.',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    canonicalPath: '/tools/unlock-pdf',
  },
];

export const toolCategories: Record<ToolCategory, { name: string; description: string }> = {
  pdf: {
    name: 'PDF Manipulation',
    description: 'Core tools to organize, compress, rotate, and manage PDF documents.',
  },
  conversion: {
    name: 'Format Conversion',
    description: 'Convert documents bi-directionally between PDF, Word, and raster image formats.',
  },
  security: {
    name: 'Security & Sovereignty',
    description: 'Encrypt, unlock, and watermark sensitive documents with zero server exposure.',
  },
  utility: {
    name: 'Advanced Utilities',
    description: 'Optical character recognition (OCR) and document indexing tools.',
  },
};